### ISSUE TITLE
Geographic columns not fully populated

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-pluto#315]
- picking up geographies from spatial district datasets is not working
700 records where school district is NULL but X/Y is not NULL.  Most may be outside of edges but not all are on boundaries.  Spatial join not seem to be consistent among no geographies.
- census block have a missing value when census tracts are populated - applies for both 2010 and 2020

**Comment by AmandaDoyle** [comment]
I think I figured out the causes for both issues.
1) fixed projection for census blocks in data lib
2) lat/longs are getting created in ocean for spatial join - haven't decided on solution

**Comment by lseirup** [comment]
If the lat/longs are in the ocean, it's OK to have null values. But this isn't the only issue. Most of the missing district data is for lots that are on land.

**Comment by Oysters1874** [comment]
After we include the step of updating null coordinates and null centroids in the building process, we should modify the sequence of carrying out functions. Spatial join should happen after this update. Based on observations, missing records for spatial join with district geometries are due to the clipped nature of the geometry datasets. The unmapped 730 points are all locating in rivers, instead of being incorrectly projected into the ocean. Maybe should change the geometry file that we use.

**Comment by Oysters1874** [comment]
As for unmapped census block, projections are different in the census tract and block file. The cb yaml for both 2020 and 2010 did not transform the data into 2263 to 4326. The projection is messed up in the dataset, therefore, the spatialjoin failed.
