### ISSUE TITLE
dof_condo Schema Change

### ISSUE THREAD

**Issue by td928** [NYCPlanning/db-pluto#347]
In the most recent version of the dof_condo file, there is change in its schema. The new mapping for the column names might need to be scoped out with help from @AmandaDoyle. At a glance, it seems like most of the columns we need are still present in the file but we need to map to new columns. 

This issue is spotted when the [last few batched of github action test ./02_build.sh step threw an error about a missing column](https://github.com/NYCPlanning/db-pluto/runs/6941386911?check_suite_focus=true). After investigating the [new version pulled on June 7th 2022](https://edm-recipes.nyc3.digitaloceanspaces.com/datasets/dof_condo/20220607/dof_condo.sql), the schema we are currently using has been depreciated.

**Comment by td928** [comment]
After some comparing to the previous versions of the dataset, this might be really simple where they simply removed `_bbl` from the names of the two columns we were working with and should be as simple as adding them removing them from our code.

**Comment by AmandaDoyle** [comment]
@td928 thanks for raising this.  To be clear the issue is that the schema of the dof_condos changed between 20220505 and 20220607.  A couple follow up questions to finalize how to move forward.
 - What fields from the `dof_condos` table are used in PLUTO?  See start of workflow [here](https://github.com/NYCPlanning/db-pluto/blob/95b5b4c3979cd5960bb6a649a57755db0998c4a0/pluto_build/sql/dedupecondotable.sql)
 - Are all fields present in the 20220607 dof_condos?
 - If so, are the values the same?
 - Then, do we change the names of the fields in the PLUTO sql scripts to match the new table names?  
 - We should confirm that DOF that this change was expected and will be how it is moving forward.

**Comment by td928** [comment]
the two columns we are using in `dedupcondotable.sql` are `condo_base_bbl` and `condo_bill_bbl`. Both of them are still available in the 20220607 version but just with new names `condo_base` and `condo_bill`.
